---
- name: Setup Linux workstation
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install common packages
      ansible.builtin.include_tasks: tasks/common-packages-main.yaml
      tags: common

    - name: Install VS Code
      ansible.builtin.include_tasks: tasks/vscode.yaml
      tags: vscode

    - name: Install Docker
      ansible.builtin.include_tasks: tasks/docker.yaml
      tags: docker

    - name: Install Helm
      ansible.builtin.include_tasks: tasks/helm.yaml
      tags: helm
