---
- name: Print current installation package
  ansible.builtin.debug:
    msg: "Installing package {{ item }}"

- name: Install common package
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
