---
- name: Print current installation package
  ansible.builtin.debug:
    msg: "Installing package {{ item }}"

- name: Install snap package
  community.general.snap:
    name: "{{ item.name }}"
    state: present
    classic: "{{ item.classic | default(false) }}"
